### PR TITLE
quesn26.c

### PR DESCRIPTION
**Pull request by SravyaChitipotu**
### Brief Description of your solution 👇
using nested for loops to find subarrays whose sum is given integer .

### CODE REVIEW

**Comment by kmvolv** [comment]
As mentioned in previous comment, avoid multiple commits

**Comment by SravyaChitipotu** [comment]
Respected sir/madam,
I am Sravya.Ch, Roll number:CS21B1024.
how to avoiding multi commits after creating a new branch. If I am creating
a new branch automatically the prevent commit is there sir, so then it's
becoming 2 commits. How to resolve this issue sir?

**Comment by kmvolv** [comment]
You could try to pull your committed changes from your forked repository every time you make a new commit.

**Comment by SravyaChitipotu** [comment]
Sir, before pushing I tried to pull also sir. But also it's the same issue.
Am I doing wrong somewhere?

**Pull request closed without merging**
